import { Pathnames } from "next-intl/navigation";
import { locales } from "./locales";

export const pathnames = {
  "/": "/",
  "/about-us": {
    de: "/ueber-uns",
    ro: "/despre-noi",
    ru: "/o-nas",
    pl: "/o-nas",
    tr: "/hakkimizda",
    ua: "/pro-nas",
    es: "/sobre-nosotros",
    ar: "/عنا",
    en: "/about-us",
  },
  "/contact": {
    de: "/kontakt",
    ro: "/contact",
    ru: "/kontakty",
    pl: "/kontakt",
    tr: "/iletisim",
    ua: "/kontakty",
    es: "/contacto",
    ar: "/اتصل",
    en: "/contact",
  },
  "/biuroservis": "/biuroservis",
  "/biuroservis/recrutation": {
    de: "/biuroservis/bewerbung",
    ro: "/biuroservis/recrutare",
    ru: "/biuroservis/nabor",
    pl: "/biuroservis/rekrutacja",
    tr: "/biuroservis/ise-alim",
    ua: "/biuroservis/nabir",
    es: "/biuroservis/reclutamiento",
    ar: "/biuroservis/التوظيف",
    en: "/biuroservis/recrutation",
  },
  "/biuroservis/housing": {
    de: "/biuroservis/wohnung",
    ro: "/biuroservis/locuinta",
    ru: "/biuroservis/zhile",
    pl: "/biuroservis/mieszkanie",
    tr: "/biuroservis/konut",
    ua: "/biuroservis/zhytlo",
    es: "/biuroservis/vivienda",
    ar: "/biuroservis/سكن",
    en: "/biuroservis/housing",
  },
  "/biuroservis/cleaning-services": {
    de: "/biuroservis/reinigungsdienste",
    ro: "/biuroservis/servicii-de-curatenie",
    ru: "/biuroservis/uborka",
    pl: "/biuroservis/uslugi-sprzatania",
    tr: "/biuroservis/temizlik-hizmetleri",
    ua: "/biuroservis/poslugi-prybyrannya",
    es: "/biuroservis/servicios-de-limpieza",
    ar: "/biuroservis/خدمات-التنظيف",
    en: "/biuroservis/cleaning-services",
  },
  "/career": {
    de: "/karriere",
    ro: "/cariera",
    ru: "/karera",
    pl: "/kariera",
    tr: "/kariyer",
    ua: "/karera",
    es: "/carrera",
    ar: "/مهنة",
    en: "/career",
  },
  "/collaboration": {
    de: "/zusammenarbeit",
    ro: "/colaborare",
    ru: "/sotrudnichestvo",
    pl: "/wspolpraca",
    tr: "/isbirligi",
    ua: "/spivpratsya",
    es: "/colaboracion",
    ar: "/تعاون",
    en: "/collaboration",
  },
  "/gallery": {
    de: "/galerie",
    ro: "/galerie",
    ru: "/galereya",
    pl: "/galeria",
    tr: "/galeri",
    ua: "/galereya",
    es: "/galeria",
    ar: "/صالة-عرض",
    en: "/gallery",
  },
  "/impressum": "/impressum",
  "/job-offers": {
    pl: "/oferty-pracy",
    de: "/stellenangebote",
    ro: "/oferte-de-munca",
    ru: "/vakansii",
    tr: "/is-ilanlari",
    ua: "/vakansii",
    es: "/ofertas-de-trabajo",
    ar: "/عروض-العمل",
    en: "/job-offers",
  },
  "/job-offers/offer": {
    de: "/stellenangebote/angebot",
    ro: "/oferte-de-munca/oferta",
    ru: "/vakansii/predlozhenie",
    pl: "/oferty-pracy/oferta",
    tr: "/is-ilanlari/teklif",
    ua: "/vakansii/propozytsiia",
    es: "/ofertas-de-trabajo/oferta",
    ar: "/عروض-العمل/عرض",
    en: "/job-offers/offer",
  },
  "/job-offers/offer/[...slug]": {
    de: "/stellenangebote/angebot/[...slug]",
    ro: "/oferte-de-munca/oferta/[...slug]",
    ru: "/vakansii/predlozhenie/[...slug]",
    pl: "/oferty-pracy/oferta/[...slug]",
    tr: "/is-ilanlari/teklif/[...slug]",
    ua: "/vakansii/propozytsiia/[...slug]",
    es: "/ofertas-de-trabajo/oferta/[...slug]",
    ar: "/عروض-العمل/عرض/[...slug]",
    en: "/job-offers/offer/[...slug]",
  },
  "/[...slug]": "/[...slug]",
} satisfies Pathnames<typeof locales>;
