export const titles = {
  index: {
    pl: "Praca w Niemczech | Oferty pracy w Niemczech | Pośrednik pracy | Visbro Personal Solutions",
    de: "Arbeiten in Deutschland | Jobangebote in Deutschland | Arbeitsvermittlung | Visbro Personal Solutions",
    ro: "Muncă în Germania | Oferte de muncă în Germania | Intermediar de muncă | Visbro Personal Solutions",
    ru: "Работа в Германии | Вакансии в Германии | Рабочее агентство | Visbro Personal Solutions",
    tr: "Almanya'da Çalışma | Almanya'da İş İlanları | İş Bulma Kurumu | Visbro Personal Solutions",
    ua: "Робота в Німеччині | Вакансії в Німеччині | Посередник з працевлаштування | Visbro Personal Solutions",
    es: "Trabajar en Alemania | Ofertas de trabajo en Alemania | Agencia de empleo | Visbro Personal Solutions",
    ar: "العمل في ألمانيا | عروض العمل في ألمانيا | وسيط العمل | حلول فيسبرو الشخصية",
    en: "Work in Germany | Job Offers in Germany | Employment Agency | Visbro Personal Solutions",
  },
} as const;

export const keywords = {
  index: {
    de: [
      "Personalvermittlung",
      "Rekrutierung",
      "Stellenvermittlung",
      "Jobvermittlung",
      "Personalsuche",
      "Kandidatensuche",
      "Bewerbermanagement",
      "Einstellung",
      "Personalbeschaffung",
      "Personalberatung",
      "Headhunting",
      "Fachkräftesuche",
      "Jobangebote",
      "Arbeitsvermittlung",
      "Karriereberatung",
      "Bewerbungsprozess",
      "Personaldienstleistungen",
      "Personalagentur",
    ],
    pl: [
      "pośrednictwo pracy",
      "rekrutacja",
      "agencja zatrudnienia",
      "rekrutowanie",
      "poszukiwanie pracowników",
      "zarządzanie kandydatami",
      "zatrudnienie",
      "pozyskiwanie pracowników",
      "doradztwo personalne",
      "headhunting",
      "poszukiwanie specjalistów",
      "oferty pracy",
      "pośrednictwo zawodowe",
      "doradztwo kariery",
      "proces rekrutacyjny",
      "usługi personalne",
      "agencja personalna",
    ],
    ro: [
      "recrutare",
      "agenție de recrutare",
      "plasare de forță de muncă",
      "căutare de candidați",
      "gestionare candidați",
      "angajare",
      "achiziție de personal",
      "consultanță în personal",
      "headhunting",
      "căutare de specialiști",
      "oferte de muncă",
      "servicii de plasare a forței de muncă",
      "consiliere în carieră",
      "proces de recrutare",
      "servicii de resurse umane",
      "agenție de personal",
    ],
    tr: [
      "işe alım",
      "işe alım ajansı",
      "işe yerleştirme",
      "aday arama",
      "aday yönetimi",
      "istihdam",
      "personel temini",
      "insan kaynakları danışmanlığı",
      "headhunting",
      "uzman arama",
      "iş ilanları",
      "işe yerleştirme hizmetleri",
      "kariyer danışmanlığı",
      "işe alım süreci",
      "insan kaynakları hizmetleri",
      "personel ajansı",
    ],
    ua: [
      "рекрутинг",
      "агенція з підбору персоналу",
      "працевлаштування",
      "пошук кандидатів",
      "управління кандидатами",
      "найм",
      "залучення персоналу",
      "кадрове консультування",
      "хедхантинг",
      "пошук спеціалістів",
      "вакансії",
      "послуги з працевлаштування",
      "консультування з кар'єри",
      "процес підбору персоналу",
      "кадрові послуги",
      "агенція з підбору кадрів",
    ],
  },
} as const;
