export const languages = {
  Russian: "русский",
  German: "Deutsch",
  French: "Français",
  Italian: "Italiano",
  English: "English",
  Spanish: "Español",
  Polish: "Polski",
  Ukrainian: "Українська",
  Romanian: "Română",
  Dutch: "Nederlands",
  Greek: "Ελληνικά",
  Czech: "Čeština",
  Swedish: "Svenska",
  Hungarian: "Magyar",
  Belarusian: "Беларуская",
  Serbian: "Српски",
  Croatian: "Hrvatski",
  Bulgarian: "Български",
  Danish: "Dansk",
  Finnish: "Suomi",
  Slovak: "Slovenčina",
  Norwegian: "Norsk",
  Albanian: "Shqip",
  Bosnian: "Bosanski",
  Estonian: "Eesti",
  Icelandic: "Íslenska",
  Irish: "Gaeilge",
  Latvian: "Latviešu",
  Lithuanian: "Lietuvių",
  Macedonian: "Македонски",
  Maltese: "Malti",
  Slovenian: "Slovenščina",
  Welsh: "Cymraeg",
  Armenian: "Հայերեն",
  Azerbaijani: "Azərbaycan",
  Basque: "Euskara",
  Catalan: "Català",
  Faroese: "Føroyskt",
  Galician: "Galego",
  Georgian: "ქართული",
  Luxembourgish: "Lëtzebuergesch",
  Occitan: "Occitan",
  Arabic: "العربية",
  Swahili: "Kiswahili",
  Hausa: "هَوُسَ",
  Igbo: "Asụsụ Igbo",
  Yoruba: "èdè Yorùbá",
  Berber: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
  Oromo: "Afaan Oromoo",
  Portuguese: "Português",
  Amharic: "አማርኛ",
  Chinese: "中文",
  Tagalog: "Tagalog",
  Vietnamese: "Tiếng Việt",
  Quechua: "Runa Simi",
  Guarani: "Avañe'ẽ",
  Aymara: "Aymar aru",
  Japanese: "日本語",
  "Mandarin Chinese": "普通话",
  Hindi: "हिन्दी",
  Bengali: "বাংলা",
  Punjabi: "ਪੰਜਾਬੀ",
  Javanese: "Basa Jawa",
  Korean: "한국어",
  Telugu: "తెలుగు",
  Marathi: "मराठी",
  Tamil: "தமிழ்",
  Urdu: "اردو",
  Turkish: "Türkçe",
  Thai: "ไทย",
  Gujarati: "ગુજરાતી",
  Jin: "晋语",
  "Southern Min": "闽南语",
  Persian: "فارسی",
  Pashto: "پښتو",
  Kannada: "ಕನ್ನಡ",
  Xiang: "湘语",
  Malayalam: "മലയാളം",
  Sundanese: "Basa Sunda",
  Oriya: "ଓଡ଼ିଆ",
  Burmese: "မြန်မာစာ",
  Hakka: "客家語/Hak-kâ-ngî",
  Bhojpuri: "भोजपुरी",
  Maithili: "मैथिली",
  Uzbek: "Oʻzbekcha",
  Sindhi: "सिन्धी, سنڌي، سندھی",
  Fula: "Fulfulde, Pulaar, Pular",
  Awadhi: "अवधी",
  "Gan Chinese": "贛語",
  Cebuano: "Sugboanon",
  Kurdish: "Kurdî, كوردی",
  "Serbo-Croatian": "српскохрватски, srpskohrvatski",
  Malagasy: "Malagasy fiteny",
  Saraiki: "سرائیکی",
  Nepali: "नेपाली",
  Sinhalese: "සිංහල",
  Chittagonian: "টগাঁইয়া",
  Zhuang: "Saɯ cueŋƅ, Saw cuengh",
};
